// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttpulhoxtkqecdoxfsdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0cHVsaG94dGtxZWNkb3hmc2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzU4MzksImV4cCI6MjA2MDIxMTgzOX0.JllLxzSmRxLX35nnQLVz8UAm8GXkPbojYQWNhZiEJQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);